<a href="https://colab.research.google.com/github/amgito1648/clase-inteligencia-artificial/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cuaderno de practicas de tipo de datos.


aqui voy a colocar ejemplos




In [1]:

import pandas as pd
import numpy as np

df = pd.read_csv(https://raw.githubusercontent.com/adiacla/bigdata/refs/heads/master/vivienda_clasificacion.csv)
df




SyntaxError: invalid syntax (<ipython-input-1-15b2013171e1>, line 4)

Numpy se usa para arreglos(Import numpy as np)

Pandas se usa para dataframes(Arreglos con diferentes datos)
un arreglo es cuando la estructura es el mismo tipo de datos(numeros)


#Ejercicios con numpy
**Crear el arreglo**

*cursiva*
##subtitulo

$a=\frac{5^n){2+i}$





In [4]:
# prompt: crear un arreglo con la variable datos, con datos sinteticos, usando numpy, donde la columna 0 es la edad y la columna1 sea las notas de IA que van de 0 a 5.

import numpy as np
datos = np.array([[np.random.randint(18, 65), np.random.uniform(0, 5)] for _ in range(10)])
datos


array([[54.        ,  1.59575123],
       [21.        ,  3.48564908],
       [45.        ,  4.6306344 ],
       [27.        ,  1.65764914],
       [46.        ,  2.85968222],
       [41.        ,  4.92970753],
       [60.        ,  1.05855154],
       [24.        ,  1.76055351],
       [48.        ,  2.52389652],
       [26.        ,  3.13500599]])

In [6]:
# prompt: calcular el promedio de a columna 1, de datos


# Calculate the average of the first column ('1') of the 'datos' array.
average = np.mean(datos[:, 1])
print(f"The average of the first column is: {average}")


The average of the first column is: 2.7637081170208355


In [7]:
type(datos)



numpy.ndarray

In [8]:
datos[0:5,0]

array([54., 21., 45., 27., 46.])

In [9]:
datos[4:6,:]

array([[46.        ,  2.85968222],
       [41.        ,  4.92970753]])

In [10]:
datos[:,:]

array([[54.        ,  1.59575123],
       [21.        ,  3.48564908],
       [45.        ,  4.6306344 ],
       [27.        ,  1.65764914],
       [46.        ,  2.85968222],
       [41.        ,  4.92970753],
       [60.        ,  1.05855154],
       [24.        ,  1.76055351],
       [48.        ,  2.52389652],
       [26.        ,  3.13500599]])

In [11]:
datos[4:6,1]

array([2.85968222, 4.92970753])

In [12]:
datos[4:6,-1]

array([2.85968222, 4.92970753])

In [13]:
identidad=np.eye(8,8)
identidad

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
identidad.shape,datos.shape

((8, 8), (10, 2))

In [18]:
# prompt: crear una lista de numpy con 20 nombre de alumnos sisteticos, en una variable llamada nombres, inventar los nombres de una lista

import numpy as np

nombres = np.array(['Ana', 'Luis', 'Sofia', 'Pedro', 'Maria', 'Carlos', 'Laura', 'David', 'Elena', 'Miguel', 'Isabel', 'Jose', 'Marta', 'Alejandro', 'Cristina', 'Daniel', 'Paula', 'Sergio', 'Andrea', 'Alberto'])
nombres

nombres


array(['Ana', 'Luis', 'Sofia', 'Pedro', 'Maria', 'Carlos', 'Laura',
       'David', 'Elena', 'Miguel', 'Isabel', 'Jose', 'Marta', 'Alejandro',
       'Cristina', 'Daniel', 'Paula', 'Sergio', 'Andrea', 'Alberto'],
      dtype='<U9')

In [19]:
# prompt: crear un dataframe llamado alumnos donde integramos el arreglo nombres,  notas_ia

import pandas as pd

notas_ia = np.random.randint(0, 101, size=len(nombres))

alumnos = pd.DataFrame({'Nombre': nombres, 'Notas_IA': notas_ia})
alumnos


Nombre  Notas_IA
0         Ana        36
1        Luis        14
2       Sofia        11
3       Pedro        10
4       Maria        32
5      Carlos        15
6       Laura        37
7       David        35
8       Elena        21
9      Miguel        21
10     Isabel       100
11       Jose        81
12      Marta        57
13  Alejandro        60
14   Cristina        30
15     Daniel        20
16      Paula        17
17     Sergio        87
18     Andrea       100
19    Alberto        89

In [20]:
alumnos.shape


(20, 2)